# Generated by Django 3.2.3 on 2021-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_alter_task_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WT', 'Waiting'), ('IM', 'Implementation'), ('TE', 'Testing'), ('RE', 'Release')], default='WT', max_length=2, verbose_name='статус задачи'),
        ),
    ]
