# Generated by Django 3.2.4 on 2021-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания проекта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Waiting'), ('Реализация', 'Implementation'), ('Проверка', 'Testing'), ('Выпуск', 'Release')], default='Ожидание', max_length=10, verbose_name='статус задачи'),
        ),
    ]
