# Generated by Django 3.2.4 on 2021-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_auto_20210610_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WT', 'Ожидание'), ('IM', 'Реализация'), ('TE', 'Проверка'), ('RE', 'Выпуск')], default='WT', max_length=2, verbose_name='статус задачи'),
        ),
    ]
